# Generated by Django 4.0.3 on 2022-04-11 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopkeeper_email', models.EmailField(max_length=100)),
                ('shopkeeper_location', models.CharField(choices=[('Library', 'Library'), ('CORE-1', 'CORE-1'), ('Lohit Hostel Stationary', 'Lohit Hostel Stationary')], max_length=100)),
                ('file', models.FileField(upload_to='media/')),
                ('no_of_copies', models.IntegerField(default=1)),
                ('black_and_white', models.BooleanField(default=True)),
                ('cost', models.IntegerField()),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
