# Generated by Django 4.0.3 on 2022-04-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order_printing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
