# Generated by Django 4.0.3 on 2022-04-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_status',
            field=models.BooleanField(default=False),
        ),
    ]
