# Generated by Django 4.0.3 on 2022-04-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order_completed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file_name',
            field=models.CharField(default='file.pdf', max_length=100),
        ),
    ]
