# Generated by Django 4.0.3 on 2022-04-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_order_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shopkeeper_email',
            field=models.EmailField(max_length=100),
        ),
    ]
