# Generated by Django 4.0.3 on 2022-04-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_order_shopkeeper_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
