# Generated by Django 4.0.3 on 2022-04-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_order_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shopkeeper_location',
            field=models.CharField(choices=[('Library', 'Library'), ('CORE-1', 'CORE-1'), ('Lohit Hostel Stationary', 'Lohit Hostel Stationary')], max_length=100),
        ),
    ]
